# Google Cloud Build configuration for building Docker image
# Usage: gcloud builds submit --config=cloudbuild.yaml

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/mosaic-signal-platform:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/mosaic-signal-platform:latest'
      - '.'

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/mosaic-signal-platform'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'mosaic-signal-platform'
      - '--image'
      - 'gcr.io/$PROJECT_ID/mosaic-signal-platform:$BUILD_ID'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--timeout'
      - '300'
      - '--port'
      - '8050'
      - '--set-env-vars'
      - 'PYTHONPATH=/app/src:/app,PREFECT_HOME=/opt/prefect,DUCKDB_THREADS=2,DASH_DEBUG=false,GCS_ENABLED=true'

images:
  - 'gcr.io/$PROJECT_ID/mosaic-signal-platform:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/mosaic-signal-platform:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'

